//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprygenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public int AgentID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string FullName { get; set; }
        public string Logo { get; set; }
        public string Priority { get; set; }
        public string PointsSale { get; set; }
        public string HistoryForSale { get; set; }
    }
}
