//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprygenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Article { get; set; }
        public string ProductName { get; set; }
        public string PtoductType { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string MinPrice { get; set; }
        public string Size { get; set; }
        public string ShippingWeight { get; set; }
        public string NetWeight { get; set; }
        public string StandartNumber { get; set; }
    }
}
