//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprygenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string INN { get; set; }
        public string CompanyType { get; set; }
        public string SupplyHistory { get; set; }
    }
}
